name: Deploy docs to GitHub pages

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  deploy:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry env use "3.10"
          poetry install

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build and deploy
        run: |
          poetry run mike deploy --push {{ steps.extract_branch.outputs.branch }}
