name: Tests (Pytest)

on: [push, pull_request]

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.7", "3.10" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'poetry'

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install -E web

      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          poetry run pytest --disable-vcr -vvv --vcr-record=none --ignore tests/utils/test_github.py --ignore tests/providers/lyrics/
        env:
          PLATFORM: ${{ matrix.platform }}
